### ISSUE TITLE
Requesting customize_embedding api failed without any error message

### ISSUE THREAD

**Issue by ZZfive** [IDEA-Research/T-Rex#51]
Using the token obtained through email, I can successfully execute "python demo_examples/generic_inference.py --token <your_token>", but "python demo_examples/customize_embedding.py --token <your_token>" always fails. The error message is as follows, and there is no error message.
![image](https://github.com/IDEA-Research/T-Rex/assets/57706634/f6c15cea-e1a4-4e64-96c3-054c61963f70)

**Comment by Mountchicken** [comment]
Hi @ZZfive 
I just updated the code and please pull the newest code. It should work fine now.

**Comment by ZZfive** [comment]
> Hi @ZZfive I just updated the code and please pull the newest code. It should work fine now.

Thanks for your response! After I pull latest code,  I successfully executed "python demo_examples/customize_embedding.py --token <your_token> ", return the url of the embedding model

**Comment by ZZfive** [comment]
Hi @Mountchicken 
The "python demo_examples/customize_embedding.py --token <your_token> " mentioned above was executed successfully, Only the token was set without any modification. However, when the prompt_image set in prompts was set to a local image, the request still failed, the output is as follows:

![image](https://github.com/IDEA-Research/T-Rex/assets/57706634/31569690-2e9a-4650-969d-d79160921a3b)

When the above failed, 8 pictures were set in prompts, and then the pictures were reduced to 4. The request was successful and the url of the embedding model was returned. **Are there any specific restrictions on the number and size of images when requesting customize_embedding?**

**Comment by Mountchicken** [comment]
The maximum number of images for `customize_embedding API` is 4, and we do not restrict the image size.

**Comment by ZZfive** [comment]
> The maximum number of images for `customize_embedding API` is 4, and we do not restrict the image size.

Is the maximum number of images for all API 4, such as generic_inference and interactve_inference?

**Comment by Mountchicken** [comment]
Yes
